/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jowright' at '21/04/15 22:37' with Gradle 1.11
 *
 * @author jowright, @date 21/04/15 22:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
